"use strict";

const content = document.getElementById("content");
const SCALER_PRESETS = [
  "Header","Sidebar","Author widget","Author byline","Article meta","Quiz",
  "Placement card","Challenge","Content footer","Explore list","Nav arrows",
  "Engagement bar","Video banner","Row spacer","Callback strip","Exit popup","Site footer"
];

// ── Storage helpers ─────────────────────────────────────────────────────────
async function loadSettings() {
  const d = {
    theme:"light", autoClean:false, scrollBehavior:true, historyEnabled:false,
    filenameTemplate:"{title} - {date}", headerFooterStamp:true,
    pdfDefaults:{ pageSize:"A4", orientation:"portrait", marginCm:0.5 },
    scalerPresets:{}, customSelectors:{}
  };
  const s = await chrome.storage.local.get(Object.keys(d));
  return { ...d, ...s };
}
async function saveSetting(key, val) {
  await chrome.storage.local.set({ [key]: val });
}

async function loadBatches() {
  const { batches } = await chrome.storage.session.get("batches");
  return batches || {};
}
async function saveBatches(b) { await chrome.storage.session.set({ batches: b }); }

// ── Router ──────────────────────────────────────────────────────────────────
const pages = { "/settings": renderSettings, "/batches": renderBatches, "/history": renderHistory, "/selectors": renderSelectors };

function route() {
  const hash = location.hash.slice(1) || "/settings";
  document.querySelectorAll(".nav-item").forEach((n) => {
    n.classList.toggle("active", n.getAttribute("href") === "#" + hash);
  });
  const fn = pages[hash] || pages["/settings"];
  content.innerHTML = "";
  fn();
}
window.addEventListener("hashchange", route);

// Apply theme
(async () => {
  const s = await loadSettings();
  applyTheme(s.theme);
  route();
  // Check for pending batch URLs from context menu
  const { pendingBatchUrl } = await chrome.storage.session.get("pendingBatchUrl");
  if (pendingBatchUrl?.length && location.hash === "#/batches") {
    await chrome.storage.session.remove("pendingBatchUrl");
    // Will be handled in renderBatches
  }
})();

function applyTheme(t) {
  if (t === "system") t = matchMedia("(prefers-color-scheme:dark)").matches ? "dark" : "light";
  document.documentElement.dataset.theme = t;
}

// ── SETTINGS PAGE ───────────────────────────────────────────────────────────
async function renderSettings() {
  const s = await loadSettings();
  content.innerHTML = `
    <div class="page-hdr"><h1>Settings</h1><p>Configure exportSculpt preferences and defaults</p></div>

    <div class="card">
      <div class="card-title">Appearance</div>
      <div class="srow">
        <div class="srow-info"><div class="srow-name">Theme</div><div class="srow-desc">Choose light, dark, or follow system</div></div>
        <div class="seg-group" id="sg-theme">
          <button class="seg ${s.theme==="light"?"on":""}" data-v="light">Light</button>
          <button class="seg ${s.theme==="dark"?"on":""}" data-v="dark">Dark</button>
          <button class="seg ${s.theme==="system"?"on":""}" data-v="system">System</button>
        </div>
      </div>
    </div>

    <div class="card">
      <div class="card-title">General</div>
      <div class="srow">
        <div class="srow-info"><div class="srow-name">Auto-clean Scaler pages</div><div class="srow-desc">Automatically remove distractions when loading Scaler articles</div></div>
        <label class="toggle"><input type="checkbox" id="t-autoclean" ${s.autoClean?"checked":""}/><span class="sl"></span></label>
      </div>
      <div class="srow">
        <div class="srow-info"><div class="srow-name">Expand horizontal scroll areas</div><div class="srow-desc">Automatically expand horizontally-scrolled sections before PDF export</div></div>
        <label class="toggle"><input type="checkbox" id="t-scroll" ${s.scrollBehavior?"checked":""}/><span class="sl"></span></label>
      </div>
      <div class="srow">
        <div class="srow-info"><div class="srow-name">Header / footer stamp in PDF</div><div class="srow-desc">Add "Generated by exportSculpt" with date and source URL</div></div>
        <label class="toggle"><input type="checkbox" id="t-stamp" ${s.headerFooterStamp?"checked":""}/><span class="sl"></span></label>
      </div>
    </div>

    <div class="card">
      <div class="card-title">History</div>
      <div class="srow">
        <div class="srow-info"><div class="srow-name">Persist history across sessions</div><div class="srow-desc">Save processed pages to local storage for later reference</div></div>
        <label class="toggle"><input type="checkbox" id="t-history" ${s.historyEnabled?"checked":""}/><span class="sl"></span></label>
      </div>
    </div>

    <div class="card">
      <div class="card-title">PDF Defaults</div>
      <div class="srow">
        <div class="srow-info"><div class="srow-name">Default page size</div></div>
        <div class="seg-group" id="sg-defsize">
          ${["A4","A3","B5","Letter"].map(v=>`<button class="seg ${s.pdfDefaults.pageSize===v?"on":""}" data-v="${v}">${v}</button>`).join("")}
        </div>
      </div>
      <div class="srow">
        <div class="srow-info"><div class="srow-name">Default orientation</div></div>
        <div class="seg-group" id="sg-deforient">
          <button class="seg ${s.pdfDefaults.orientation==="portrait"?"on":""}" data-v="portrait">Portrait</button>
          <button class="seg ${s.pdfDefaults.orientation==="landscape"?"on":""}" data-v="landscape">Landscape</button>
        </div>
      </div>
      <div class="srow">
        <div class="srow-info"><div class="srow-name">Filename template</div>
          <div class="srow-desc">Variables: {title} {date} {time} {domain}</div></div>
        <input class="input input-sm" id="inp-filename" value="${s.filenameTemplate}"/>
      </div>
    </div>

    <div class="card">
      <div class="card-title">Scaler Element Presets</div>
      <p style="font-size:12px;color:var(--text2);margin-bottom:12px">Toggle which elements to remove on Scaler article pages.</p>
      <div class="preset-grid" id="presets-grid">
        ${SCALER_PRESETS.map(p=>`<label class="preset-item"><input type="checkbox" data-preset="${p}" ${s.scalerPresets[p]!==false?"checked":""}/>${p}</label>`).join("")}
      </div>
    </div>
    <div class="flex-c mt-m"><button class="btn btn-pri" id="btn-save-settings">Save Settings</button></div>
  `;

  // Wire segmented controls
  content.querySelectorAll(".seg-group").forEach(g => {
    g.querySelectorAll(".seg").forEach(b => {
      b.addEventListener("click", () => {
        g.querySelectorAll(".seg").forEach(x => x.classList.remove("on"));
        b.classList.add("on");
        if (g.id === "sg-theme") { saveSetting("theme", b.dataset.v); applyTheme(b.dataset.v); }
      });
    });
  });

  // Wire toggles
  const bindToggle = (id, key) => {
    document.getElementById(id)?.addEventListener("change", (e) => saveSetting(key, e.target.checked));
  };
  bindToggle("t-autoclean","autoClean"); bindToggle("t-scroll","scrollBehavior");
  bindToggle("t-stamp","headerFooterStamp"); bindToggle("t-history","historyEnabled");

  // Save button
  document.getElementById("btn-save-settings")?.addEventListener("click", async () => {
    const presets = {};
    content.querySelectorAll("[data-preset]").forEach(cb => { presets[cb.dataset.preset] = cb.checked; });
    await saveSetting("scalerPresets", presets);
    const defSz = content.querySelector("#sg-defsize .seg.on")?.dataset.v || "A4";
    const defOr = content.querySelector("#sg-deforient .seg.on")?.dataset.v || "portrait";
    await saveSetting("pdfDefaults", { pageSize: defSz, orientation: defOr, marginCm: 0.5 });
    await saveSetting("filenameTemplate", document.getElementById("inp-filename")?.value || "{title} - {date}");
    const btn = document.getElementById("btn-save-settings");
    btn.textContent = "Saved!"; btn.style.background = "var(--ok)";
    setTimeout(() => { btn.textContent = "Save Settings"; btn.style.background = ""; }, 1500);
  });
}

// ── BATCHES PAGE ────────────────────────────────────────────────────────────
async function renderBatches() {
  const batches = await loadBatches();
  const batchList = Object.values(batches).sort((a,b) => b.created - a.created);

  content.innerHTML = `
    <div class="page-hdr"><h1>Batch Process</h1><p>Create batches of pages to export as a single zipped PDF download</p></div>
    <div class="flex-c mb-m">
      <input class="input" id="new-batch-name" placeholder="Batch name (e.g. DSA Concepts)"/>
      <button class="btn btn-pri" id="btn-new-batch">Create Batch</button>
    </div>
    <div id="batches-list">${batchList.length ? "" : '<div class="empty"><div class="ico">&#9776;</div>No batches yet. Create one above.</div>'}</div>
  `;

  const listEl = document.getElementById("batches-list");

  function renderBatchCards() {
    loadBatches().then(bs => {
      const list = Object.values(bs).sort((a,b) => b.created - a.created);
      if (!list.length) { listEl.innerHTML = '<div class="empty"><div class="ico">&#9776;</div>No batches yet.</div>'; return; }
      listEl.innerHTML = list.map(b => {
        const counts = { queued:0, processing:0, done:0, failed:0 };
        (b.items||[]).forEach(i => counts[i.status]++);
        const total = (b.items||[]).length;
        const pct = total ? Math.round((counts.done / total) * 100) : 0;
        return `
        <div class="card" data-bid="${b.id}">
          <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px">
            <div>
              <div style="font-size:14px;font-weight:700">${esc(b.name)}</div>
              <div style="font-size:11px;color:var(--text3)">${total} items &middot;
                <span class="badge-s badge-done">${counts.done} done</span>
                ${counts.failed?`<span class="badge-s badge-failed">${counts.failed} failed</span>`:""}
                ${counts.processing?`<span class="badge-s badge-processing">processing</span>`:""}
              </div>
            </div>
            <div class="flex-c">
              ${b.status!=="processing"?`<button class="btn btn-pri btn-sm" data-start="${b.id}" ${total===0?"disabled":""}>Start</button>`:""}
              ${counts.done>0?`<button class="btn btn-sec btn-sm" style="color:var(--ok);border-color:var(--ok)" data-dlzip="${b.id}">&#8681; Download Zip</button>`:""}
              ${counts.failed?`<button class="btn btn-sec btn-sm" style="color:var(--warn);border-color:var(--warn)" data-retry="${b.id}">Retry ${counts.failed} Failed</button>`:""}
              <button class="btn btn-err btn-sm" data-del="${b.id}">&times;</button>
            </div>
          </div>
          ${b.status==="processing"?`<div style="background:var(--border);border-radius:4px;height:6px;margin-bottom:10px;overflow:hidden"><div style="background:var(--pri);height:100%;width:${pct}%;transition:width .3s;border-radius:4px"></div></div>`:""}
          ${b.status==="partial"?`<div style="background:var(--warn-l);border:1px solid var(--warn);border-radius:var(--rs);padding:8px 10px;margin-bottom:10px;font-size:12px;color:#92400e;display:flex;align-items:center;gap:8px"><span style="font-size:16px">&#9888;</span><span>${counts.failed} item${counts.failed===1?"":"s"} failed. You can <strong>download the ${counts.done} completed PDF${counts.done===1?"":"s"}</strong> or retry the failed items.</span></div>`:""}
          <div style="margin-bottom:8px;display:flex;gap:6px">
            <input class="input" style="flex:1;width:auto" id="add-url-${b.id}" placeholder="Paste URL or use current tab"/>
            <button class="btn btn-sec btn-sm" data-addurl="${b.id}">Add URL</button>
            <button class="btn btn-sec btn-sm" data-addtab="${b.id}">Add Current Tab</button>
          </div>
          <div class="srow" style="border:none;padding:6px 0">
            <div class="srow-info"><div class="srow-name" style="font-size:11px">Batch defaults</div></div>
            <div class="seg-group" data-batchsize="${b.id}">
              ${["A4","A3","B5","Letter"].map(v=>`<button class="seg ${(b.settings?.pageSize||"A4")===v?"on":""}" data-v="${v}">${v}</button>`).join("")}
            </div>
            <div class="seg-group" data-batchorient="${b.id}" style="margin-left:6px">
              <button class="seg ${(b.settings?.orientation||"portrait")==="portrait"?"on":""}" data-v="portrait">Port.</button>
              <button class="seg ${(b.settings?.orientation||"portrait")==="landscape"?"on":""}" data-v="landscape">Land.</button>
            </div>
          </div>
          <div id="items-${b.id}">
            ${(b.items||[]).map((it,idx) => `
              <div class="batch-item">
                <span class="badge-s badge-${it.status}">${it.status}</span>
                <span class="url" title="${esc(it.url)}">${esc(it.title||it.url)}</span>
                <div class="actions"><button class="btn btn-sec btn-sm" data-rmitem="${b.id}:${idx}">&times;</button></div>
              </div>
            `).join("")}
          </div>
        </div>`;
      }).join("");
      wireCardEvents();
    });
  }

  function wireCardEvents() {
    content.querySelectorAll("[data-start]").forEach(b => b.addEventListener("click", async () => {
      // Save batch settings first
      const bid = b.dataset.start;
      const bs = await loadBatches(); const batch = bs[bid]; if (!batch) return;
      const szEl = content.querySelector(`[data-batchsize="${bid}"] .seg.on`);
      const orEl = content.querySelector(`[data-batchorient="${bid}"] .seg.on`);
      batch.settings = { pageSize: szEl?.dataset.v||"A4", orientation: orEl?.dataset.v||"portrait", marginCm:0.5 };
      batch.items.forEach(it => { if (it.status!=="done") it.status = "queued"; });
      await saveBatches(bs);
      chrome.runtime.sendMessage({ type: "startBatch", batchId: bid });
      renderBatchCards();
    }));
    content.querySelectorAll("[data-retry]").forEach(b => b.addEventListener("click", () => {
      chrome.runtime.sendMessage({ type: "retryFailed", batchId: b.dataset.retry });
      setTimeout(renderBatchCards, 500);
    }));
    content.querySelectorAll("[data-del]").forEach(b => b.addEventListener("click", async () => {
      const bs = await loadBatches(); delete bs[b.dataset.del]; await saveBatches(bs); renderBatchCards();
    }));
    content.querySelectorAll("[data-addurl]").forEach(b => b.addEventListener("click", async () => {
      const bid = b.dataset.addurl;
      const inp = document.getElementById("add-url-" + bid);
      const url = inp?.value.trim(); if (!url) return;
      const bs = await loadBatches(); if (!bs[bid]) return;
      bs[bid].items.push({ id:"i_"+Date.now(), url, title: url, status:"queued", overrides:null, error:null });
      await saveBatches(bs); inp.value = ""; renderBatchCards();
    }));
    content.querySelectorAll("[data-addtab]").forEach(b => b.addEventListener("click", async () => {
      const bid = b.dataset.addtab;
      // Get the most recent non-extension tab in the current window
      const allTabs = await chrome.tabs.query({ currentWindow: true });
      const extUrl = chrome.runtime.getURL("");
      const userTab = allTabs.find(t => !t.url.startsWith(extUrl) && !t.url.startsWith("chrome-extension://")
        && !t.url.startsWith("chrome://") && !t.url.startsWith("edge://"))
        || allTabs.filter(t => t.url.startsWith("http")).pop();
      if (!userTab) return;
      const bs = await loadBatches(); if (!bs[bid]) return;
      bs[bid].items.push({ id:"i_"+Date.now(), url:userTab.url, title:userTab.title||userTab.url, status:"queued", overrides:null, error:null });
      await saveBatches(bs); renderBatchCards();
    }));
    content.querySelectorAll("[data-dlzip]").forEach(b => b.addEventListener("click", () => {
      chrome.runtime.sendMessage({ type: "downloadZip", batchId: b.dataset.dlzip });
    }));
    content.querySelectorAll("[data-rmitem]").forEach(b => b.addEventListener("click", async () => {
      const [bid, idx] = b.dataset.rmitem.split(":");
      const bs = await loadBatches(); if (!bs[bid]) return;
      bs[bid].items.splice(+idx, 1); await saveBatches(bs); renderBatchCards();
    }));
    // Wire seg controls inside batch cards
    content.querySelectorAll(".card .seg-group").forEach(g => {
      g.querySelectorAll(".seg").forEach(b => {
        b.addEventListener("click", () => {
          g.querySelectorAll(".seg").forEach(x => x.classList.remove("on"));
          b.classList.add("on");
        });
      });
    });
  }

  // Create new batch
  document.getElementById("btn-new-batch")?.addEventListener("click", async () => {
    const name = document.getElementById("new-batch-name")?.value.trim();
    if (!name) return;
    const bs = await loadBatches();
    const id = "b_" + Date.now();
    bs[id] = { id, name, created:Date.now(), items:[], settings:{ pageSize:"A4", orientation:"portrait", marginCm:0.5 }, status:"idle" };
    await saveBatches(bs);
    document.getElementById("new-batch-name").value = "";
    renderBatchCards();
  });

  renderBatchCards();

  // Listen for batch updates from background
  chrome.runtime.onMessage.addListener((msg) => {
    if (msg.type === "batchUpdate") renderBatchCards();
  });
}

// ── HISTORY PAGE ────────────────────────────────────────────────────────────
async function renderHistory() {
  const { history } = await chrome.storage.local.get("history");
  const list = history || [];

  content.innerHTML = `
    <div class="page-hdr"><h1>History</h1><p>Pages you have processed with exportSculpt</p></div>
    <div class="search">
      <input class="input" id="history-search" placeholder="Search by title or URL\u2026"/>
      <button class="btn btn-err btn-sm" id="clear-history">Clear All</button>
    </div>
    <div id="history-table"></div>
  `;

  function renderTable(filter) {
    const f = (filter || "").toLowerCase();
    const filtered = f ? list.filter(h => (h.title||"").toLowerCase().includes(f) || (h.url||"").toLowerCase().includes(f)) : list;
    const el = document.getElementById("history-table");
    if (!filtered.length) {
      const s = loadSettings();
      el.innerHTML = '<div class="empty"><div class="ico">&#128338;</div>' +
        (list.length ? "No results match your search." : "No history yet. Enable history persistence in Settings.") + '</div>';
      return;
    }
    el.innerHTML = `<table class="tbl"><thead><tr><th>Date</th><th>Title</th><th>URL</th><th>Format</th></tr></thead><tbody>
      ${filtered.slice(0,100).map(h => `<tr>
        <td style="white-space:nowrap">${new Date(h.timestamp).toLocaleDateString()} ${new Date(h.timestamp).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</td>
        <td>${esc(h.title||"-")}</td>
        <td><a href="${esc(h.url)}" target="_blank">${esc((h.url||"").slice(0,60))}</a></td>
        <td><span class="badge-s badge-done">${h.format}</span></td>
      </tr>`).join("")}
    </tbody></table>`;
  }

  renderTable("");
  document.getElementById("history-search")?.addEventListener("input", (e) => renderTable(e.target.value));
  document.getElementById("clear-history")?.addEventListener("click", async () => {
    await chrome.storage.local.set({ history: [] });
    renderHistory();
  });
}

// ── SELECTORS PAGE ──────────────────────────────────────────────────────────
async function renderSelectors() {
  const s = await loadSettings();
  const cs = s.customSelectors || {};
  const domains = Object.keys(cs).sort();

  content.innerHTML = `
    <div class="page-hdr"><h1>Custom Selectors</h1><p>Define CSS selectors to remove on specific websites. These are saved and auto-applied.</p></div>
    <div class="card">
      <div class="card-title">Add New Domain</div>
      <div class="flex-c">
        <input class="input" id="new-domain" placeholder="e.g. www.example.com"/>
        <button class="btn btn-pri btn-sm" id="btn-add-domain">Add Domain</button>
      </div>
    </div>
    <div id="domains-list">${domains.length ? "" : '<div class="empty"><div class="ico">&#10010;</div>No custom selectors yet. Add a domain above.</div>'}</div>
  `;

  function renderDomains() {
    loadSettings().then(s2 => {
      const cs2 = s2.customSelectors || {};
      const doms = Object.keys(cs2).sort();
      const el = document.getElementById("domains-list");
      if (!doms.length) { el.innerHTML = '<div class="empty"><div class="ico">&#10010;</div>No custom selectors yet.</div>'; return; }
      el.innerHTML = doms.map(d => {
        const site = cs2[d];
        return `<div class="card">
          <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:10px">
            <div class="flex-c">
              <label class="toggle"><input type="checkbox" data-domain-toggle="${d}" ${site.enabled?"checked":""}/><span class="sl"></span></label>
              <span style="font-size:13px;font-weight:700">${esc(d)}</span>
            </div>
            <button class="btn btn-err btn-sm" data-del-domain="${d}">&times; Remove</button>
          </div>
          <div id="sels-${d.replace(/\./g,"_")}">
            ${(site.selectors||[]).map((sel,i) => `<div class="sel-item"><span>${esc(sel)}</span><span class="x" data-rm-sel="${d}:${i}">&times;</span></div>`).join("")}
          </div>
          <div class="flex-c mt-m">
            <input class="input" style="flex:1;width:auto;font-family:monospace;font-size:12px" id="add-sel-${d.replace(/\./g,"_")}" placeholder=".ad-banner, #popup, [class*='modal']"/>
            <button class="btn btn-sec btn-sm" data-add-sel="${d}">Add Selector</button>
          </div>
        </div>`;
      }).join("");

      // Wire events
      el.querySelectorAll("[data-domain-toggle]").forEach(cb => cb.addEventListener("change", async (e) => {
        const ss = await loadSettings(); const cc = ss.customSelectors || {};
        if (cc[e.target.dataset.domainToggle]) cc[e.target.dataset.domainToggle].enabled = e.target.checked;
        await saveSetting("customSelectors", cc);
      }));
      el.querySelectorAll("[data-del-domain]").forEach(b => b.addEventListener("click", async () => {
        const ss = await loadSettings(); const cc = ss.customSelectors || {};
        delete cc[b.dataset.delDomain]; await saveSetting("customSelectors", cc); renderDomains();
      }));
      el.querySelectorAll("[data-add-sel]").forEach(b => b.addEventListener("click", async () => {
        const dom = b.dataset.addSel;
        const inp = document.getElementById("add-sel-" + dom.replace(/\./g,"_"));
        const val = inp?.value.trim(); if (!val) return;
        const ss = await loadSettings(); const cc = ss.customSelectors || {};
        if (!cc[dom]) cc[dom] = { selectors:[], enabled:true };
        cc[dom].selectors.push(val); await saveSetting("customSelectors", cc);
        inp.value = ""; renderDomains();
      }));
      el.querySelectorAll("[data-rm-sel]").forEach(b => b.addEventListener("click", async () => {
        const [dom, idx] = b.dataset.rmSel.split(":");
        const ss = await loadSettings(); const cc = ss.customSelectors || {};
        if (cc[dom]) { cc[dom].selectors.splice(+idx, 1); await saveSetting("customSelectors", cc); renderDomains(); }
      }));
    });
  }

  document.getElementById("btn-add-domain")?.addEventListener("click", async () => {
    const d = document.getElementById("new-domain")?.value.trim().toLowerCase();
    if (!d) return;
    const ss = await loadSettings(); const cc = ss.customSelectors || {};
    if (!cc[d]) cc[d] = { selectors:[], enabled:true };
    await saveSetting("customSelectors", cc);
    document.getElementById("new-domain").value = "";
    renderDomains();
  });

  renderDomains();
}

// ── Utility ─────────────────────────────────────────────────────────────────
function esc(s) { const d = document.createElement("div"); d.textContent = s || ""; return d.innerHTML; }
